---
name: OpenMM
version: 0.0.1
main: MeTooIDK\OpenMM\Main
api: 5.3.1
src-namespace-prefix: MeTooIDK\OpenMM
commands:
  openmm:
    description: OpenMurderMystery Command
    usage: "/openmm <start/newmap/set_map_spawn>"
    permission: openmm.permission
permissions:
 openmm.permission:
    description: "OpenMM Command"
    default: op
...
